### ISSUE TITLE
LDAP Portal: 同じアカウント名でフォームが送れてしまう

### ISSUE THREAD

**Issue by kino-ma** [nkzwlab/ldap-portal#2]
LDAP にすでに存在するアカウント名で登録フォームを送れてしまう。

フォームの時点で弾くのはセキュリティ的な懸念がある。  
つまり、あるアカウント名が存在することがわかると、ブルートフォースの対象となってしまう。

それはそうと、フォームの送信は成功したうえでバックエンドで受け付けない処理があるべき。  
その時に Slack で通知したりするといい感じ？

**Comment by feles-ao42** [comment]
やった。えらい。
